### ISSUE TITLE
Unable to import it not in CommonJS if install via npm, because npm ignores dist folder

### ISSUE THREAD

**Issue by dimadk24** [crookedneighbor/markdown-it-link-attributes#20]
npm ignores dist folder, where all minified and optimized code lies:

https://github.com/crookedneighbor/markdown-it-link-attributes/blob/ccb21ca5b81ed8328fc6ff5070cac62d0397694d/.npmignore#L2

Because of that people who want to use project and install it via npm can't access minified, optimized code. But why do you minify code, if minified version isn't accessible to developers, who use this package? And I believe most people prefer to install it via npm, rather than via github.

Files in dist folder are not only minified and optimized, but (what is much more important) they are accessible for different require systems. Current [index.js](https://github.com/crookedneighbor/markdown-it-link-attributes/blob/master/index.js) can be imported only by CommonJS (in other package systems it throws `module is not defined` error).

But on top of [dist/markdown-it-link-attributes.js](https://github.com/crookedneighbor/markdown-it-link-attributes/blob/master/dist/markdown-it-link-attributes.js) file there's a check for `module` and `exports`, which makes possible to import package not only in CommonJS.

But because `dist` folder isn't on npm you can't access package in other JS package systems, if you install package via npm.

Let's add `dist` folder to files, which are deployed to npm :)

**Comment by dimadk24** [comment]
For now if you use package system other than CommonJS the only possible solution is to install this package from github:
```shell
npm install https://github.com/crookedneighbor/markdown-it-link-attributes/tarball/v2.1.0
```
Note, perhaps you need to update version in command above to get latest version of the package.

**Comment by crookedneighbor** [comment]
Feel free to open a pr.

**Comment by dimadk24** [comment]
Sure, will do!

**Comment by crookedneighbor** [comment]
Out in v3.0.0 https://github.com/crookedneighbor/markdown-it-link-attributes/releases/tag/v3.0.0
