### ISSUE TITLE
Feature Request: VS Code Extension Support

### ISSUE THREAD

**Issue by rdhar** [crookedneighbor/markdown-it-link-attributes#25]
Hi,

First off, thank you for sharing this project: it's ideal for bringing a [much](https://stackoverflow.com/questions/4425198/can-i-create-links-with-target-blank-in-markdown) [requested](https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link) [feature](https://stackoverflow.com/questions/32359583/markdown-link-opening-in-new-tab) support to Markdown.

It seems this would be perfect for a VS Code extension, especially with their in-built support of [markdown-it plugins](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-support-for-new-syntax-with-markdownit-plugins).

```js
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  return {
    extendMarkdownIt(md: any) {
      return md.use(require('markdown-it-emoji'));
    }
  };
}
```

Hope this can be considered as a feature request, thanks for your time.

**Comment by crookedneighbor** [comment]
What's involved in doing this?

**Comment by rdhar** [comment]
Do you mean with [developing a VS Code extension](https://code.visualstudio.com/api/get-started/your-first-extension) in general?

**Comment by crookedneighbor** [comment]
I don't understand the relation of developing a vs code extension and this repo. Wouldn't it be a separate project?

**Comment by rdhar** [comment]
That's true, the only link is the request to support a dedicated VS extension for this [markdown-it plugin](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-support-for-new-syntax-with-markdownit-plugins).

Some examples include:

- [Markdown TOC](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc)
    Implementation of a single plugin.
- [Extra Markdown Plugins](https://marketplace.visualstudio.com/items?itemName=xpol.extra-markdown-plugins)
    Implementation of several markdown-it plugins.

**Comment by crookedneighbor** [comment]
That's out of the scope for this project. But feel free to do that yourself!
