### ISSUE TITLE
incomatible with markdown-it-attrs

### ISSUE THREAD

**Issue by binyamin** [crookedneighbor/markdown-it-link-attributes#26]
**Problem**
I can't add an extra rel value to individual links. Normally I would load the [markdown-it-attrs](https://github.com/arve0/markdown-it-attrs) plugin, and format it as `[text](example.org){rel=me}`. Current behavior is to override any existing value(s).

**Solution**
Preserve any existing rel value(s).
https://github.com/crookedneighbor/markdown-it-link-attributes/blob/8ce6d9e31060218af509b113ce965f4094f7fe6c/index.js#L36-L38

Note: this applies to class names as well as the rel attribute.

**Comment by crookedneighbor** [comment]
Feel free to open a PR.

**Comment by binyamin** [comment]
@crookedneighbor should I add markdown-it-attrs as a dev-dependency, for testing?

**Comment by crookedneighbor** [comment]
I'd rather replicate what it is basically doing, rather than have it as a dependency itself.

**Comment by crookedneighbor** [comment]
IE, something more generic than the exact thing it's doing, and not need to keep it up to date as new versions are released.

**Comment by binyamin** [comment]
I simply implemented a custom plugin: https://github.com/binyamin/binyam.in/commit/eeaf7770a72f7d7aff85446930279578ffca060a
Feel free to take a look.
