### ISSUE TITLE
Add Match function instead of only RegExp

### ISSUE THREAD

**Issue by drwharris** [crookedneighbor/markdown-it-link-attributes#27]
I have just had to implement a series of chained regexes to try and identify if a href is local or external. To say it was a pain would be an understatement (no fault of this library!). It got me thinking that it would have been easier, in this instance, if instead of specifying a regex pattern, you could specify a function in its place

var md = require('markdown-it')()
var mila = require('markdown-it-link-attributes')

So instead of:
```
md.use(mila, {
  attrs: {
    pattern: /^https:/,
    target: '_blank',
    rel: 'noopener'
  }
})
```

You could do something like:
```
md.use(mila, {
  attrs: {
    matcher: (link) => { return link.startsWith('https:') },
    target: '_blank',
    rel: 'noopener'
  }
})
```

Thoughts?

**Comment by crookedneighbor** [comment]
Go ahead and PR it. Happy to release a major version that uses this instead.

**Comment by drwharris** [comment]
> Go ahead and PR it. Happy to release a major version that uses this instead.

Great, Ill get onto that.

**Comment by drwharris** [comment]
@crookedneighbor is there a reason that "markdown-it" isn't in devDependancies ? I cant get tests to run unless its there.

**Comment by crookedneighbor** [comment]
Sorry for the delay!

The reason for not having an explicit dev dependency was because in ci, I was testing against multiple versions of markdown-it: https://github.com/crookedneighbor/markdown-it-link-attributes/blob/8ce6d9e31060218af509b113ce965f4094f7fe6c/.travis.yml#L4-L10

Though, there's probably a better way to handle it now then when I first set this up.

**Comment by crookedneighbor** [comment]
Merged in your PR after making some tweaks. It's now called `matcher` instead of `function` and I've dropped `pattern` entirely.

Out now in v4.0.0
