### ISSUE TITLE
README not updated for 4.0.0

### ISSUE THREAD

**Issue by brycewray** [crookedneighbor/markdown-it-link-attributes#29]
The README hasn't yet been updated for 4.0.0 (specifically, the item addressed in https://github.com/crookedneighbor/markdown-it-link-attributes/issues/27) to include the same information on the [NPM page for this package](https://www.npmjs.com/package/markdown-it-link-attributes). Also, 4.0.0 isn't yet shown in the releases here on GH.

**Comment by crookedneighbor** [comment]
This is fixed now.
