### ISSUE TITLE
Trouble with Multiple Configurations method (pattern matching)

### ISSUE THREAD

**Issue by SonicMagna** [crookedneighbor/markdown-it-link-attributes#30]
Perhaps I'm not using this correctly, but I can not get the Multiple Configurations method of passing an Array of Configurations to work as advertised.
This relates to "markdown-it-link-attributes": "4.0.0"
This is in a React App, in conjunction with MarkdownIt.
Using this code from this package's page:
```
const mdParser = new MarkdownIt({
  html: true,
  linkify: false, // I've tried with and without this
});

const mila = require('markdown-it-link-attributes');
mdParser.use(mila,[
  {
    pattern: /^https?:\/\//,
    attrs: {
      class: 'external-link',
      target: '_blank',
      rel: 'noopener noreferrer',
    },
  },
  {
    pattern: /^\//,
    attrs: {
      class: 'absolute-link',
    },
  }
]);
```

Markdown:
```
[google](https://www.google.com)
[home](/home)
 ```
Results:
```
<a href=\"https://www.google.com\" class=\"external-link\" target=\"_blank\" rel=\"noopener noreferrer\">google</a>
<a href=\"/home\" class=\"external-link\" target=\"_blank\" rel=\"noopener noreferrer\">home</a>
```
It results in every link, external or local, having the attributes from the first pattern assigned.

As an experiment I swapped the pattern order to:
`pattern: /^\//,` is before `pattern: /^https?:\/\//,`
and that results in:
```
[google](https://www.google.com) 
<a href=\"https://www.google.com/\" class=\"absolute-link\">google</a>
```
**To me, it seems that it's not applying pattern matching at all. It's just adding the attributes from the first `attrs:{}` it encounters in the array. It's behaving like the standard Basic Configuration usage.**
As a side note, is this intended to accept regex flags like case insensitive etc.?

As a test I also tried this code:
```
 mdParser.use(mila, {
    matcher(href) {
      return href.startsWith('http');
    },
    attrs: {
      target: '_blank',
      rel: 'noopener noreferrer',
    },
  });
```

Markdown:
```
[google](https://www.google.com)  
[home](/home)
 ```
Results:
```
<a href=\"https://www.google.com\" target=\"_blank\" rel=\"noopener noreferrer\">google</a>
<a href=\"/home\">home</a><br>\n<a href=\"home\">home</a>
```
  
So that results as expected; ie an href that begins with http will get the attributes, ones that are local such as `/home` do not.
Problem with this approach is we are not specifying case insensitive. So for the above, 'HTTP' would not match.
I changed the code to this to get case insensitive:
```
mdParser.use(mila, {
  matcher(href) {
    const h = href.toLowerCase();
    return h.startsWith('http');
  },
  attrs: {
    target: '_blank',
    rel: 'noopener noreferrer',
  },
});
```
Feedback?
Thanks

**Comment by crookedneighbor** [comment]
Ahh, I see what's wrong. I dropped the `pattern` attribute in favor of `matcher` function in v4.0.0 of the library, but missed some spots in the README when doing the update in the docs.

You should just be able to do this:

```js
mdParser.use(mila, {
  matcher(href) {
    return href.match(/^https?:\/\//g)
  },
  attrs: {
    target: '_blank',
    rel: 'noopener noreferrer',
  },
});
```

**Comment by crookedneighbor** [comment]
Whoops, meant to use the array version in the example:

```js
mdParser.use(mila, [{
  matcher(href) {
    return href.match(/^https?:\/\//g)
  },
  attrs: {
    target: '_blank',
    rel: 'noopener noreferrer',
  },
}, {
  // other config
});
```
