### ISSUE TITLE
error Error TypeError: link.attrIndex is not a function

### ISSUE THREAD

**Issue by zackyjc** [crookedneighbor/markdown-it-link-attributes#32]
I'm using `markdown-it` as a parser to convert my markdown document into `html`, and I'm using two plugins for this: `markdown-it-toc-and-anchor` and `markdown-it-link-attributes`: the former is used to obtain a separated block of TOC data, and the latter is used to add personalized attributes to links. But when the document has chapter flags like '#' '##', I get the following error:

```
- error Error [TypeError]: link.attrIndex is not a function
at findFirstMatchingConfig (/Users/yangjincan/workspace/myblog/node_modules/markdown-it-link-attributes/index.js:7:30)
at md.renderer.rules.link_open  (/Users/yangjincan/workspace/myblog/node_modules/markdown-it-link-attributes/index.js:64:18)
at md.renderer.rules.link_open (/Users/yangjincan/workspace/myblog/node_modules/markdown-it-alert/dist/index.js:46:20)
at Renderer.renderInline (/Users/yangjincan/workspace/myblog/node_modules/markdown-it/lib/renderer.js:275:28)
at Renderer.render (/Users/yangjincan/workspace/myblog/node_modules/markdown-it/lib/renderer.js:330:22)
at MarkdownIt.render (/Users/yangjincan/workspace/myblog/node_modules/markdown-it/lib/index.js:544:24)
at mdparserMarkdownIt (webpack-internal:///(api)/./src/libs/md/markdown-it/mdparser.js:169:31)
at mdparser (webpack-internal:///(api)/./src/libs/md/parser.js:28:77)
```

This error can be reproduced: https://npm.runkit.com/markdown-it-link-attributes?t=1692132423255

The test code as following:

```
var md = require("markdown-it")();

var markdownItTocAndAnchor = require('markdown-it-toc-and-anchor').default;
md.use(markdownItTocAndAnchor);

var mila = require("markdown-it-link-attributes");
md.use(mila, {
  attrs: {
    target: "_blank",
    rel: "noopener",
  },
});

const content1 = '\n\n# title1\nfoo\n\n## title2\n\n[Example](https://example.com)\n\n# title3\n\nbar\n\n'; // error
const content2 = '#' // error
const content3 = '\n\n title1\n\nfoo\n\n title2\n\n[Example](https://example.com)\n\n title3\n\nbar\n\n'; // ok

const content = content2;
var result = md.render(content);
```

I don't know the cause of the problem, is there any help? How can I use both plugins?

**Comment by zackyjc** [comment]
Here is a test code link: https://runkit.com/embed/31oj05bktvhp

**Comment by crookedneighbor** [comment]
Thanks for the thorough report! I probably won’t get a chance to look at this today, but ping me in a few days if I haven’t posted a follow up.

**Comment by crookedneighbor** [comment]
OK, I figured out the problem. It's actually a problem in the toc plugin. You can see here: https://github.com/medfreeman/markdown-it-toc-and-anchor/blob/708434d7965924e4bf79090b5fd758a2a1cec011/src/index.js#L29-L45

Instead of returning Tokens, they are converting them to plain objects, so it's missing the `attrIndex` function.

If it was like this instead:

```js
const renderAnchorLinkSymbol = options => {
  if (options.anchorLinkSymbolClassName) {
    const spanOpenToken = new Token("span_open", "span", 1);
    spanOpenToken.attrs = [["class", options.anchorLinkSymbolClassName]];

    const spanCloseToken = new Token("text", "", 0);
    spanCloseToken.content = options.anchorLinkSymbol;


    return [
      spanOpenToken,
      spanCloseToken,
      new Token("span_close", "span", -1)
    ];
  } else {
    const token = new Token("text", "", 0)
    token.content = options.anchorLinkSymbol

    return [
      token
    ];
  }
};
```

it would work (and updating the other parts of the code where they are doing the same thing).

So the other plugin will need an update for it to work correctly.
